In [1]:
import numpy as np

In [33]:
n_choices=5

M = np.random.uniform(size=(n_choices,n_choices))

Dl = np.tril(M,-1)
Du = np.tril((1-M),-1)

D = Dl + Du.T + np.diag([.5]*n_choices)


In [34]:
D

array([[0.5       , 0.32037163, 0.22227595, 0.76657676, 0.34495778],
       [0.67962837, 0.5       , 0.24604354, 0.70096408, 0.15999291],
       [0.77772405, 0.75395646, 0.5       , 0.48238773, 0.13362842],
       [0.23342324, 0.29903592, 0.51761227, 0.5       , 0.2683173 ],
       [0.65504222, 0.84000709, 0.86637158, 0.7316827 , 0.5       ]])

In [39]:
n_experts = 5

D = np.zeros((n_experts, n_choices, n_choices))

for e in range(n_experts):
    M = np.random.uniform(size=(n_choices,n_choices))

    Dl = np.tril(M,-1)
    Du = np.tril((1-M),-1)
    
    D[e,:,:] = Dl + Du.T + np.diag([.5]*n_choices)
    

In [41]:
D[1,:,:]

array([[0.5       , 0.77679732, 0.2838396 , 0.49348664, 0.22831887],
       [0.22320268, 0.5       , 0.68375752, 0.50405064, 0.75097315],
       [0.7161604 , 0.31624248, 0.5       , 0.40352921, 0.40673859],
       [0.50651336, 0.49594936, 0.59647079, 0.5       , 0.8045521 ],
       [0.77168113, 0.24902685, 0.59326141, 0.1954479 , 0.5       ]])

array([[1.        , 0.4289719 , 0.53732071, 0.88638299, 0.69748597],
       [1.        , 1.        , 0.1282974 , 0.3636023 , 0.18301506],
       [1.        , 1.        , 1.        , 0.06175839, 0.09564214],
       [1.        , 1.        , 1.        , 1.        , 0.3036321 ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])